### ISSUE TITLE
Cool Documentation Need + (Animation's ex)

### ISSUE THREAD

**Issue by cinaaaa** [E-RROR/react-tagify#11]
We Love Cool Animation for Our Project ... Please Attach Gifs and Modern Design Concepts to Show Demo Of Our Project

**Comment by SimonHoiberg** [comment]
Have you considered included a demo page in the project?
You could have a separate folder in your repository called 'demo', which includes a React App that consumes the `ReactTagify` component. You can then link to this page as a gh-page and people can see the component in action for themselves :slightly_smiling_face: 
(Maybe some coolness where you can change the text in an editor, and it updates the UI rendered by `ReactTagify`)

This will also make it easier for future development, to have a "sandbox" to try the new features in.

**Comment by cinaaaa** [comment]
Sure **@Silind** ... I Will Make a Sandbox for React Tagify Tomorrow ... You Alway Have Cool Ideas 
; )
