### ISSUE TITLE
Hover functionality for hashtag and mention

### ISSUE THREAD

**Issue by saeedPadyab** [E-RROR/react-tagify#25]
Hi Sina, hope you are doing well and thanks for the awesome library. 

Currently Hashtags and mentions are clickable. it that possible for you to add **Hover** functionality for those?
I need to show a popup for mentions.

thanks in advance.

**Comment by cinaaaa** [comment]
Hi @saeedPadyab , thanks for your interest in react-tagify library.
Unfortunately updating react tagify can't be done in force but thanks for your note, I'll do it but you can look for alternative libraries to have that kind of feature for now 🙏
