### ISSUE TITLE
Writing Test for Code's

### ISSUE THREAD

**Issue by cinaaaa** [E-RROR/react-tagify#3]
**Is your feature request related to a problem? Please describe.**
I Need Good and Clear Testing Code for Our Project
You'r All Welcome

**Comment by cinaaaa** [comment]
Need Help Guys ... im Too Busy

**Comment by theashraf** [comment]
I'd like to help, Can I work on this?

**Comment by cinaaaa** [comment]
> I'd like to help, Can I work on this?

Of course : )
You Can Add Anything You like Just mind That The Main Thing That We Have to Keep That Is React Tagify and We Need To Tagify The Text's : )

**Comment by cinaaaa** [comment]
> I'd like to help, Can I work on this?

But Writing Test Is Really Important ; )

**Comment by theashraf** [comment]
> > I'd like to help, Can I work on this?
> 
> Of course : )
> You Can Add Anything You like Just mind That The Main Thing That We Have to Keep That Is React Tagify and We Need To Tagify The Text's : )

Cool, I'll just unit test the existing functionalities

**Comment by cinaaaa** [comment]
> > > I'd like to help, Can I work on this?
> > 
> > 
> > Of course : )
> > You Can Add Anything You like Just mind That The Main Thing That We Have to Keep That Is React Tagify and We Need To Tagify The Text's : )
> 
> Cool, I'll just unit test the existing functionalities

That's great @theashraf
