### ISSUE TITLE
Any Improvement Accepted : )

### ISSUE THREAD

**Issue by cinaaaa** [E-RROR/react-tagify#4]
Any Improvement accepted for project but make attention to the topic of this project " React Tagify"

**Comment by sanjsanj** [comment]
The example is a little political and polarising.

```
<p>I Love My Country #USA #united_states </p>
And Also My President @trump
<span>And My #lovely #parents </span>
<div>But I Hate @iran</div>
```

I'm happy you have opinions and can express them in the free society in which you live, but what if people don't share your opinion?

Just my opinion; I don't care who likes or dislikes individuals or countries but the message puts me off.  A more neutral example might be more broadly appealing and inclusive.

**Comment by cinaaaa** [comment]
> The example is a little political and polarising.
> 
> ```
> <p>I Love My Country #USA #united_states </p>
> And Also My President @trump
> <span>And My #lovely #parents </span>
> <div>But I Hate @iran</div>
> ```
> 
> I'm happy you have opinions and can express them in the free society in which you live, but what if people don't share your opinion?
> 
> Just my opinion; I don't care who likes or dislikes individuals or countries but the message puts me off. A more neutral example might be more broadly appealing and inclusive.

Yeah ... Its Good Opinion Man...
I Think Its Changes Now : )

**Comment by cinaaaa** [comment]
Please Open **new Issue** to add new improvement
